version: 2
enable-beta-versions: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"